services:
  db:
    image: mysql:8.0
    container_name: mysql_db_user_service
    ports: 
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - services_default

networks:
  services_default:
    external: true